backend:
  name: git-gateway
  branch: main # or "master" depending on your repo

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "images/uploads"
    create: true
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "string" }
